CFLAGS=-Wall -Wextra -g

all: ex1/ex1 ex3/ex3

#Build targets 
ex1/ex1: ex1/ex1.c
	gcc $(CFLAGS) -o ex1/ex1 ex1/ex1.c

ex3/ex3: ex3/ex3.c
	gcc $(CFLAGS) -c ex3/ex3 ex3/ex3.c

clean:
	rm -f ex1/ex1 ex3/ex3

