Table creation

CREATE TABLE STUDENT37
( 
STUDID      CHAR(5)       NOT NULL , 
STUDNAME    VARCHAR(20)   NOT NULL , 
SCONC       CHAR(13)      NOT NULL ,
SEMAIL      VARCHAR(20)   NOT NULL ,
SADD        CHAR(50)      NOT NULL ,
SSTRM       VARCHAR(10)   NOT NULL ,
SYOP        NUMBER(4)     NOT NULL ,
SGEN        CHAR(1)       NOT NULL ,
CONSTRAINT  PK1   PRIMARY KEY(STUDID),
CONSTRAINT  U1    UNIQUE(SCONC)       ,
CONSTRAINT  CK1   CHECK(LENGTH(SCONC)=13) , 
CONSTRAINT  CK2   CHECK(SCONC LIKE '+91') ,
CONSTRAINT  CK3   CHECK(SUBSTR(SCONC, 4,1) IN (6,7,8,9)),
CONSTRAINT  U2    UNIQUE(SEMAIL),
CONSTRAINT  CK4   CHECK((SEMAIL NOT LIKE '@%') AND
						 (SEMAIL LIKE '%@%' AND
						 SEMAIL NOT LIKE '%@%@%') AND 
						(SEMAIL LIKE '%.COM')),
CONSTRAINT CK5   CHECK(INSTR(SEMAIL,'@',1,1) < INSTR(SEMAIL,'.',1,1)),
CONSTRAINT CK6   CHECK(LENGTH(SYOP)=4)
)


select * from t1 where regexp_like(data,'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}');



CREATE TABLE EMAILDATA
(
	EMAIL VARCHAR(50) NOT NULL,
	CONSTRAINT  CK10    CHECK(regexp_like(EMAIL,'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'))
)

INSERT INTO EMAILDATA VALUES('user@example.com')

INSERT INTO EMAILDATA VALUES('user.com@example')

INSERT INTO STUDENT37 VALUES('S01','SUNDRA','+919910075077','sas@mail.COM','PUNE','ECE','2021','M')